# Generated by Django 2.2.10 on 2020-06-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=8)),
                ('site_name', models.CharField(max_length=16)),
                ('zip_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=16)),
                ('connections', models.ManyToManyField(related_name='_device_connections_+', to='topomapper.Device')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='topomapper.Location')),
            ],
        ),
    ]
