# Generated by Django 2.2.10 on 2020-06-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0002_auto_20200614_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='connections',
        ),
    ]
