# Generated by Django 2.2.10 on 2020-06-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0003_remove_device_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_devices', to='topomapper.Device')),
                ('to_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_devices', to='topomapper.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='connections',
            field=models.ManyToManyField(related_name='connected_to', through='topomapper.Link', to='topomapper.Device'),
        ),
    ]
