# Generated by Django 2.2.10 on 2020-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0004_auto_20200615_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='failure',
            field=models.BooleanField(default=False),
        ),
    ]
