# Generated by Django 2.2.10 on 2020-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0005_auto_20200618_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sim_root_routes',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
