# Generated by Django 2.2.10 on 2020-06-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0006_device_sim_root_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='from_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_devices', to='topomapper.Device'),
        ),
        migrations.AlterField(
            model_name='link',
            name='to_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_devices', to='topomapper.Device'),
        ),
    ]
