# Generated by Django 2.2.10 on 2020-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0007_auto_20200620_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='connections',
        ),
        migrations.AddField(
            model_name='device',
            name='connected_to',
            field=models.ManyToManyField(related_name='connections', through='topomapper.Link', to='topomapper.Device'),
        ),
    ]
