# Generated by Django 2.2.10 on 2020-06-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0008_auto_20200620_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='root_routes',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sim_root_routes',
        ),
    ]
