# Generated by Django 2.2.10 on 2020-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0009_auto_20200620_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='connected_to',
        ),
        migrations.AddField(
            model_name='device',
            name='uplinks',
            field=models.ManyToManyField(related_name='downlinks', through='topomapper.Link', to='topomapper.Device'),
        ),
    ]
