# Generated by Django 2.2.10 on 2020-06-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0011_auto_20200620_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure', models.BooleanField(default=False)),
                ('downdevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updevices', to='topomapper.Device')),
                ('updevice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downdevices', to='topomapper.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='uplinks',
            field=models.ManyToManyField(related_name='downlinks', through='topomapper.Link', to='topomapper.Device'),
        ),
    ]
