# Generated by Django 2.2.10 on 2020-06-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0014_auto_20200620_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sim_check',
            field=models.BooleanField(default=False),
        ),
    ]
