# Generated by Django 2.2.10 on 2020-06-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topomapper', '0015_device_sim_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='from_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_devices', to='topomapper.Device'),
        ),
    ]
